config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/the-master-controller', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'join', to:'pages#join'
  #get 'donate', to:'pages#donate'
  get 'projects', to:'pages#project'
  get 'volunteers', to:'pages#volunteer'
  post 'volunteers', to:'volunteer#create'
  get 'help-us', to:'pages#help'
  get 'error', to:'pages#error'




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord

has_one_attached :image

    rails_admin do
      create do
        field :image
        field :title
        field :description
        field :time
        field :nop
      end

      edit do
        field :image
        field :title
        field :description
        field :time
        field :nop
      end
      show do
        field :image
        field :title
        field :description
        field :time
        field :nop
      end
      list do
        field :image
        field :title
        field :time
      end
    end

end

app/models/slideshow.rb
class Slideshow < ApplicationRecord
  has_one_attached :image


  rails_admin do
    create do
      field :image
      field :title
      field :caption
    end

    edit do
      field :image
      field :title
      field :caption
    end
    show do
      field :image
      field :title
      field :caption
    end
    list do
      field :image
      field :title
      field :caption
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable


  rails_admin do
    create do
      field :email
      field :password
    end

    edit do
      field :email
      field :password
    end
    show do
      field :email
      field :password
    end
    list do
      field :email
      field :created_at
    end
  end


end

app/models/volunteer.rb
class Volunteer < ApplicationRecord

  has_one_attached :image

  validates :first_name,:last_name,:age,:gender,:address,:profession,:image, presence: true

  private


  rails_admin do
    create do
      field :image
      field :first_name
      field :last_name
      field :age
      field :gender , :enum do
        enum do
          [['MALE','MALE'],['FEMALE','FEMALE'],['OTHER','OTHER']]
        end
      end
      field :address
      field :contact
      field :email
      field :blood_group , :enum do
        enum do
          [['A+','A+'],['A-','A-'],['B+','B+'],['B-','B-'],['O+','O+'],['O-','O-'],['AB+','AB+'],['AB-','AB-']]
        end
      end

      # field :profession , :enum do
      #   enum do
      #     [['Doctor','Doctor'],['Lawyer','Lawyer'],['Engineer','Engineer']]
      #   end
      # end

      field :profession

      field :description

      field :active

    end

    edit do
      field :image
      field :first_name
      field :last_name
      field :age
      field :gender , :enum do
        enum do
          [['MALE','MALE'],['FEMALE','FEMALE'],['OTHER','OTHER']]
        end
      end
      field :address
      field :contact
      field :email
      field :blood_group , :enum do
        enum do
          [['A+','A+'],['A-','A-'],['B+','B+'],['B-','B-'],['O+','O+'],['O-','O-'],['AB+','AB+'],['AB-','AB-']]
        end
      end
      # field :profession , :enum do
      #   enum do
      #     [['Doctor','Doctor'],['Lawyer','Lawyer'],['Engineer','Engineer']]
      #   end
      # end

      field :profession

      field :description

      field :active

    end
    list do
      field :first_name
      field :last_name
      field :contact
      field :email
      field :active
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @images = Slideshow.all
    end

    def join
        @volunteer = Volunteer.new
    end



    def project
        @projects = Project.order(:id).page params[:page]
    end

    def volunteer
        @volunteers = Volunteer.where('active = true')

    end

    def help
    end

    def error

    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController



end

app/controllers/volunteer_controller.rb
class VolunteerController < ApplicationController

  def create
    @volunteer = Volunteer.new(volunteer_params)
    @volunteer.profession.upcase!


    check_params(@volunteer)

    if @volunteer.save
      redirect_to root_path
    else
      render 'pages/join'
    end
  end



  private

  def check_params(params)
    if params.gender == 'Gender*'
      params.gender = ''
    end

    if params.profession == 'PROFESSION*' or params.profession == 'OTHER'
      params.profession = ''
    end

    if params.blood_group == 'Blood Group*'
      params.blood_group = ''
    end
  end

  def volunteer_params
    params.require(:volunteer).permit(:first_name,:last_name,:age,:gender,:address,:contact,:email,:blood_group,:description,:profession,:active,:image)
    #debugger
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/_footer.html.erb
<!-- Footer Area Start -->
<!-- Footer -->
<footer class="page-footer font-small bg-dark" id="footer">

<!-- Footer Elements -->
<div class="container">

  <!-- Grid row-->
  <div class="row">

    <!-- Grid column -->
    <div class="col-md-12 py-5">
      <div class="mb-4 flex-center">

        <!-- Facebook -->
        <a class="fb-ic" href="https://www.facebook.com/aasrafoundationjaipur16" target="_blank">
          <i class="fab fa-facebook-f fa-lg black-text mr-md-5 mr-3 fa-2x"> </i>
        </a>
        <!--Instagram-->
        <a class="ins-ic" href="https://www.instagram.com/aasrafoundationjaipur/" target="_blank">
          <i class="fab fa-instagram fa-lg black-text mr-md-5 mr-3 fa-2x"> </i>
        </a>
        <!--LinkedIn-->
        <a class="ins-ic" href="https://www.linkedin.com/company/aasrafoundationjaipur" target="_blank">
          <i class="fab fa-linkedin-in fa-lg black-text mr-md-5 mr-3 fa-2x"></i>
        </a>
        <!-- Twitter -->
        <a class="tw-ic" href="https://twitter.com/aasrafound_jpr" target="_blank">
          <i class="fab fa-twitter fa-lg black-text mr-md-5 mr-3 fa-2x"> </i>
        </a>
        <!-- Whatsapp-->
        <a class="gplus-ic" href="https://wa.me/917014015902" target="_blank">
          <i class="fab fa-whatsapp fa-lg black-text mr-md-5 mr-3 fa-2x"></i>
        </a>
      </div>
    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row-->

</div>
<!-- Footer Elements -->

<!-- Copyright -->
<div class="footer-copyright text-center black-text py-3">© 2019 Copyright:
  <a href="http://www.theaasrafoundation.org/" class="black-text"> WWW.THEAASRAFOUNDATION.ORG</a>
</div>
<!-- Copyright -->

</footer>

<script>
var stick;
if(stick)
  {
    document.getElementById('footer').classList.add('sticky-bottom')
  }
else {
  document.getElementById('footer').classList.remove('sticky-bottom')
}

</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark sticky-top" >
  <%= link_to image_tag("A2.png", class: 'navbar-brand navbar-logo img-circle', style: 'margin-left:10%;'), root_path %>
  <button class="navbar-toggler" id="toggler" type="button" data-toggle="collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-md-center" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item" id='home'>
        <%= link_to 'HOMEPAGE', root_path, class: 'nav-link', style: 'color:#000' %>
      </li>
      <li class="nav-item" id='join'>
        <%= link_to 'JOIN US', join_path, class: 'nav-link', style: 'color:#000' %>
      </li>
      <li class="nav-item" id='volunteers'>
        <%= link_to 'OUR VOLUNTEERS', volunteers_path, class: 'nav-link', style: 'color:#000' %>
      </li>

      <li class="nav-item" id='projects'>
        <%= link_to 'OUR PROJECTS', projects_path, class: 'nav-link', style: 'color:#000' %>
      </li>

      <li class="nav-item" id="help-us">
        <div class="dropdown" id="dropdownClass">
          <div class=" dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            HELP US
          </div>
        </div>
      </li>



      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" id="dropdown-menu">

      </div>


    </ul>
  </div>
</nav>



<div id="overlay" onclick="off()"></div>








<script>

  // Overlay Function
    function on() {
        document.getElementById("overlay").style.display = "block";
    }

    function off() {
        document.getElementById("overlay").style.display = "none";
    }


    var show = false;
    var dropdown = false;
    var nav = document.getElementById('navbarSupportedContent');

    document.getElementById('toggler').addEventListener('click', function () {
        if (!show) {
            nav.classList.add('show');
            show = true;
            on();
        } else {
            nav.classList.remove('show');
            show = false;
            if(dropdown){
                dropdown = false
            }
            off();
        }
    });



    document.getElementById('overlay').addEventListener('click', function () {
        if (document.getElementById("overlay").style.display = "none") {
            nav.classList.remove('show');
            show = false;
        }
    });


    var urls = ['join', 'projects', 'volunteers', 'help-us'];
    var url = 'home';
    urls.forEach(function (item, index) {
        if (window.location.href.indexOf(item) > -1) {
            url = urls[index];
        }
    });
    document.getElementById(url).classList.add('active-nav');
    document.getElementById(url).children[0].style.color = "#fff"

    function updown()
    {
        if (!dropdown) {
            document.getElementById("dropdownMenuLink").setAttribute("aria-expanded", true);
            document.getElementById('dropdownClass').classList.add('show');
            document.getElementById('dropdown-menu').classList.add('show');
            dropdown = !dropdown;

        } else {
            document.getElementById("dropdownMenuLink").setAttribute("aria-expanded", false);
            document.getElementById('dropdownClass').classList.remove('show');
            document.getElementById('dropdown-menu').classList.remove('show');
            dropdown = !dropdown;

        }
    }

    document.getElementById('dropdownMenuLink').addEventListener('click',function () {
        updown();

    });

    document.addEventListener('click', function(e) {
        e = e || window.event;
        var target = e.target || e.srcElement;
            elementClass=target.classList[0];
            if ((elementClass != 'dropdown-item' || elementClass != 'dropdown-toggle' || elementClass != 'dropdownMenuLink') && dropdown)
            {
                document.getElementById("dropdownMenuLink").setAttribute("aria-expanded", false);
                document.getElementById('dropdownClass').classList.remove('show');
                document.getElementById('dropdown-menu').classList.remove('show');
                //dropdown = false;
            }

    }, true);


    if(window.location.href.indexOf('help-us') > -1)
    {
        const drop = '<a class="dropdown-item" href="#donate">Donate</a>\n' +
            '<a class="dropdown-item" href="#volunteer">Volunteer</a>\n' +
            '<a class="dropdown-item" href="#partnership">Partnership</a>'+
            '<a class="dropdown-item" href="#intern">Internship</a>'+
            '<a class="dropdown-item" href="#vv">Virtual Volunteer</a>';
        document.getElementById('dropdown-menu').insertAdjacentHTML('afterbegin',drop);
    }
    else{
        const drop = '<a class="dropdown-item" href="help-us/#donate">Donate</a>\n' +
            '<a class="dropdown-item" href="help-us/#volunteer">Volunteer</a>\n' +
            '<a class="dropdown-item" href="help-us/#partnership">Partnership</a>'+
            '<a class="dropdown-item" href="help-us/#intern">Internship</a>'+
            '<a class="dropdown-item" href="help-us/#vv">Virtual Volunteer</a>';
        document.getElementById('dropdown-menu').insertAdjacentHTML('afterbegin',drop);
    }


</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>


  <% if content_for? :for_head %>
    <%= yield :for_head %>
  <%else %>
  <% end %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= favicon_link_tag 'favicon.ico' %>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <% if content_for? :for_scripts %>
    <%= yield :for_scripts %>
  <%else %>
  <% end %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>

  <%= render partial: "layouts/navbar" unless content_for :navbar%>
    <% if notice%>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong><%= notice %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% elsif alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong><%= alert %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' unless content_for :footer%>







    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/js/mdb.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/donate.html.erb
<div class="conatainer laptop" id="donate">
  <div class="card" style="width:95%;margin:auto">
    <div class="card-body">
      <h2 class="h3-responsive font-weight-bold text-center my-5" style="color:#007bff" >Donation</h2>

      <div class="container">
        <div class="row">
          <div class="col"></div>
          <div class="col pad">
            <input type="button" class="toggle-button btn-block button-active btn-pad" value="Paytm" id="paytm" style="width: 260px; border-radius: 0px; box-shadow: 0px 0px 0px;"/>
          </div>
          <div class="col pad">
            <input type="button" class="toggle-button btn-block btn-pad" value="UPI" id="upi" style="width: 260px; border-radius: 0px; box-shadow: 0px 0px 0px;"/>
          </div>
          <div class="col pad">
            <input type="button" class="toggle-button btn-block btn-pad" value="Bank" id="bank" style="width: 260px; border-radius: 0px; box-shadow: 0px 0px 0px;"/>
          </div>
          <div class="col"></div>
        </div>
      </div>
      <div class="container" style="margin-bottom: 1%">
        <div class="row">
          <div class="col"></div>
          <div class="payment-block col-9 pad" id="payment-block">
            <img src="<%= image_path('paytm.jpeg') %>" class="photos" style="height: 500px">
          </div>
          <div class="col"></div>
        </div>
      </div>




      <script type="text/javascript">
          var addActiveClass = function(buttonPressed){
              document.getElementById('paytm').classList.remove('button-active');
              document.getElementById('upi').classList.remove('button-active');
              document.getElementById('bank').classList.remove('button-active');
              buttonPressed.classList.add("button-active");
          }

          document.getElementById('paytm').addEventListener('click',function(){

              addActiveClass(document.getElementById('paytm'));
              var block=document.getElementById('payment-block');
              block.innerHTML='<img src="<%= image_path('paytm.jpeg') %>" class="photos" style="height: 500px">';
          })

          document.getElementById('upi').addEventListener('click',function(){

              addActiveClass(document.getElementById('upi'));
              var block=document.getElementById('payment-block');
              block.innerHTML='<img src="<%= image_path('upi.png') %>" class="photos" style="height: 500px">';
          })

          document.getElementById('bank').addEventListener('click',function(){

              addActiveClass(document.getElementById('bank'));
              var block=document.getElementById('payment-block');
              block.innerHTML='<img src="<%= image_path('bank.png') %>" class="photos" style="height: 500px">';
          })
      </script>

    </div>
  </div>
</div>




<!--Mobile View-->

<div class="conatainer mobile" id="donate">
  <div class="card" style="width:95%;margin:auto">
    <div class="card-body">
      <h2 class="h3-responsive font-weight-bold text-center my-5" style="color:#007bff" >Donation</h2>

      <div class="container" style="margin-bottom: 5%">
        <div class="row">
          <div class="col-lg-12">
            <input type="button" class="toggle-button btn-block button-active" value="Paytm" id="paytm1"/>
          </div>
          <div>
            <img src="<%= image_path('paytm.jpeg') %>" class="photos show mobile-photos" id="paytm-img">
          </div>
          <div class="col-lg-12">
            <input type="button" class="toggle-button btn-block" value="UPI" id="upi1"/>
          </div>
          <div>
            <img src="<%= image_path('upi.png') %>" class="photos show mobile-photos" id="upi-img">
          </div>
          <div class="col-lg-12">
            <input type="button" class="toggle-button btn-block" value="Bank" id="bank1"/>
          </div>
          <div>
            <img src="<%= image_path('bank.png') %>" class="photos show mobile-photos" id="bank-img">
          </div>
        </div>
      </div>
    </div>
  </div>


  <script>
    function init(){
        document.getElementById('bank-img').classList.add('hide');
        document.getElementById('upi-img').classList.add('hide');
        document.getElementById('paytm-img').classList.add('hide');
        document.getElementById('upi-img').classList.remove('show');
        document.getElementById('bank-img').classList.remove('show');
        document.getElementById('paytm1').classList.remove('button-active');
        document.getElementById('upi1').classList.remove('button-active');
        document.getElementById('bank1').classList.remove('button-active');
    }

      init();
      document.getElementById('paytm1').addEventListener('click',function(){
          init();
          document.getElementById('paytm-img').classList.add('show');
          document.getElementById('paytm-img').classList.remove('hide');
          document.getElementById('paytm1').classList.add('button-active');
      });

      document.getElementById('upi1').addEventListener('click',function(){
          init();
          document.getElementById('upi-img').classList.add('show');
          document.getElementById('upi-img').classList.remove('hide');
          document.getElementById('upi1').classList.add('button-active')
      });

      document.getElementById('bank1').addEventListener('click',function(){
          init();
          document.getElementById('bank-img').classList.add('show');
          document.getElementById('bank-img').classList.remove('hide');
          document.getElementById('bank1').classList.add('button-active')
      });
  </script>
</div>

app/views/pages/error.html.erb
<% if @volunteer.errors.any? %>
  <div class="row">
    <div class="col">
      <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <ul>
          <% @volunteer.errors.full_messages.each do |msg| %>
            <li class="text-justify"><%= msg %></li>
          <%end %>
        </ul>
      </div>
    </div>
  </div>
<%end %>

app/views/pages/help.html.erb
<% content_for :for_head do %>
  <title>Help Us | Aasra</title>
  <meta name="description" content="Help Aasra Foundation through various options"/>
<% end %>




<div class="container-fluid" >
<div class="row" style="padding-bottom:5%">
  <div class="col-2"></div>
    <div class="col-8">
      <h2 class="h1-responsive font-weight-bold text-center my-5">How can you help?</h2>
      <!-- Section description -->
      <p class="lead grey-text text-center w-responsive mx-auto mb-5">Even a small amount of your time and effort can make a large difference. You can help and support in various ways.</p>
    </div>
    <div class="col-2"></div>
</div>
</div>

<div class="conatainer" id="donate">

    <%= render template: "pages/donate" %>

</div>

<h2 class="h2-responsive font-weight-bold text-center my-5" style="padding-top:3%">Some Other Ways to Help...</h2>

<div class="container" style="padding-top:1%">
<div class="row" >




  <div class="container" style="padding-top:1%">
    <div class="row">

      <div class="col" style="padding-bottom:10%" id="volunteer">
        <div class="card" style="border-radius: 5%">
          <div class="card-body text-center" style="height: 330px;">
            <i class="fas fa-user-tie image" style="border-radius:50%;margin:auto;padding:5%;font-size: 400%;"></i>
            <!-- <img src="https://picsum.photos/200/200" class="img" alt="No Image"
              style="border-radius:50%;margin:auto;padding:5%" /> -->
            <h4 class="card-title"> Volunteer</h4>
            <p class="card-text">Join us hand in hand and make an impact. Get in touch to become a volunteer</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" style="width: 100%;">More
              Information</a>
          </div>
        </div>
      </div>



      <div class="col" style="padding-bottom:10%" id="partnership">
        <div class="card" style="border-radius: 5%">
          <div class="card-body text-center" style="height: 330px;">
            <i class="far fa-handshake image" style="border-radius:50%;margin:auto;padding:5%;font-size: 400%;"></i>
            <h4 class="card-title"> Partnerships</h4>
            <p class="card-text">If you share the same vision as us, please contact and collaborate with us.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" style="width: 100%;">More
              Information</a>
          </div>
        </div>
      </div>

    </div>



    <div class="row">

      <div class="col" style="padding-bottom:10%" id="intern">
        <div class="card" style="border-radius: 5%">
          <div class="card-body text-center" style="height: 330px;">
            <i class="fas fa-graduation-cap image" style="border-radius:50%;margin:auto;padding:5%;font-size: 400%;"></i>
            <h4 class="card-title"> Internships</h4>
            <p class="card-text">We are running programs, where you can apply as an Intern. Reach out to us for more
              information.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter"  style="width: 100%;">More
              Information</a>
          </div>
        </div>
      </div>

      <div class="col" style="padding-bottom:10%" id="vv">
        <div class="card" style="border-radius: 5%">
          <div class="card-body text-center" style="height: 330px;">
            <i class="fas fa-desktop image" style="border-radius:50%;margin:auto;padding:5%;font-size: 400%;"></i>
            <h4 class="card-title">Virtual Volunteer</h4>
            <p class="card-text">We understand being physically present is not always possible, but that does not
              restrict you to make an impact. You can still support and make your contribution to the cause virtually.
            </p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" style="width: 100%;">More
              Information</a>
          </div>
        </div>
      </div>

    </div>

  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
       aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">More Information</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Reach out to us for more information.</p>
          <p><a href="mailto: aasrafoundationjaipur@gmail.com"><i class="fas fa-envelope" style="color: #CF776F; padding-right: 10px;"></i>Aasra Foundation Mail</a></p>
          <p><a href="tel:+91-7014015902"><i class="fas fa-id-badge"  style="color: dodgerblue; padding-right: 10px;"></i>Mangla Sharma (+91-7014015902)</a></p>
          <p><a href="https://www.facebook.com/aasrafoundationjaipur16/"><i class="fab fa-facebook-square" style="color: #3D5A99;  padding-right: 10px;"></i>Aasra Foundation Facebook Page</a></p>


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger btn-block" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
</div>